use async_trait::async_trait;
use empath_common::context::Context;

use crate::types::SpooledMessageId;

/// Trait for the underlying storage mechanism
///
/// This trait defines the core operations for message storage backends.
/// Implementations can store messages in memory, on disk, in databases, etc.
///
/// # Trait Object Safety
/// This trait uses `async_trait` to remain dyn-safe, allowing for
/// `Arc<dyn BackingStore>` trait objects. While this adds a small Box
/// allocation per async call (~10-20ns), this overhead is negligible
/// compared to I/O operations (microseconds to milliseconds).
///
/// # Security
/// Implementations must:
/// - Validate all inputs (especially IDs to prevent path traversal)
/// - Handle concurrent access safely
/// - Prevent data corruption during writes
#[async_trait]
pub trait BackingStore: Send + Sync + std::fmt::Debug {
    /// Write a context to the backing store and return its tracking ID
    ///
    /// The tracking ID is generated by the backing store and is guaranteed to be unique.
    /// The tracking ID will be set in the context's `tracking_id` field.
    ///
    /// # Errors
    /// Returns an error if the context cannot be written
    async fn write(&self, context: &mut Context) -> crate::Result<SpooledMessageId>;

    /// List all message identifiers
    ///
    /// Messages should be returned in sorted order (by creation time, lexicographically)
    ///
    /// # Errors
    /// Returns an error if the backing store cannot be read
    async fn list(&self) -> crate::Result<Vec<SpooledMessageId>>;

    /// Read a specific message and return its full context
    ///
    /// # Errors
    /// Returns an error if the message cannot be found or read
    async fn read(&self, id: &SpooledMessageId) -> crate::Result<Context>;

    /// Update an existing message in the backing store
    ///
    /// This allows updating the context (especially delivery metadata) without
    /// changing the tracking ID. Used by the delivery processor to persist
    /// delivery state changes.
    ///
    /// # Errors
    /// Returns an error if the message cannot be found or updated
    async fn update(&self, id: &SpooledMessageId, context: &Context) -> crate::Result<()>;

    /// Delete a message
    ///
    /// # Errors
    /// Returns an error if the message cannot be deleted
    async fn delete(&self, id: &SpooledMessageId) -> crate::Result<()>;
}
