version: 2

updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "server"
      - "dependencies"
    groups:
      dependencies:
        patterns:
          - "*"
