name: Analyze - Commits

on: [pull_request]

jobs:
  committed:
    name: Analyze - Commits
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v5

      - name: Lint Commits
        uses: crate-ci/committed@master
        with:
          args: "-vv"
          commits: "HEAD"
