name: Analyze - Server

on:
  push:
    branches: ["master","main"]
    paths:
      - "**/*.rs"
      - "Cargo.toml"
      - "Cargo.lock"
  pull_request:
    branches: ["master","main"]
    paths:
      - "**/*.rs"
      - "Cargo.toml"
      - "Cargo.lock"

jobs:
  analyze-clippy:
    env:
      RUNNER_TOOL_CACHE: /toolcache
      RUSTFLAS: "-Dwarnings"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - uses: rui314/setup-mold@v1

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: clippy

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/      
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run rust-clippy
        run: cargo clippy --all-targets --all-features

      - name: Run rust-fmt
        run: cargo fmt --all -- --check

  test-server:
    env:
      RUNNER_TOOL_CACHE: /toolcache
      RUSTFLAS: -Dwarnings
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - uses: rui314/setup-mold@v1

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: clippy miri

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/      
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install nextest
        uses: taiki-e/install-action@v2
        with: 
          tool: nextest

      - name: Test Server
        run: MIRIFLAGS="-Zmiri-disable-isolation" cargo miri nextest run && cargo test --doc
