use std::env;
use std::path::PathBuf;

use cbindgen::{Config, Language, ParseConfig};

fn main() -> anyhow::Result<()> {
    let dependencies = vec![
        String::from("empath-common"),
        String::from("empath-ffi"),
        String::from("empath-smtp"),
        String::from("empath-spool"),
    ];

    let package_name = env::var("CARGO_PKG_NAME")?;
    let out_dir = env::var("OUT_DIR")?;
    let output_file = PathBuf::from(&format!("{out_dir}/../../../../{package_name}.h"));

    let config = Config {
        language: Language::C,
        cpp_compat: true,
        pragma_once: true,
        autogen_warning: Some(String::from(
            "/**
 * Warning, this file is autogenerated by cbindgen. Don't modify this manually.
 * Instead, alter build.rs, or the respective rust item.
 */",
        )),
        after_includes: Some(
            "\n#define EM_DECLARE_MODULE(ty, ...) Mod declare_module() { return (Mod){ty ## Listener, {__VA_ARGS__}}; }".to_owned(),
        ),
        parse: ParseConfig {
            parse_deps: true,
            include: Some(dependencies.clone()),
            extra_bindings: dependencies,
            ..Default::default()
        },
        ..Default::default()
    };

    cbindgen::generate_with_config(".", config)?.write_to_file(output_file);

    Ok(())
}
