#!/bin/bash
#
# Simple SMTP client example - sends a test email through Empath
#
# Usage: ./send_email.sh [host] [port]
#
# Defaults: localhost:1025

set -euo pipefail

HOST="${1:-localhost}"
PORT="${2:-1025}"

echo "=== Sending test email via SMTP ==="
echo "Server: $HOST:$PORT"
echo ""

# Send SMTP commands via netcat
{
    echo "EHLO example.com"
    sleep 0.1
    echo "MAIL FROM:<sender@example.com>"
    sleep 0.1
    echo "RCPT TO:<recipient@example.com>"
    sleep 0.1
    echo "DATA"
    sleep 0.1
    cat <<'EMAIL'
From: sender@example.com
To: recipient@example.com
Subject: Test Email from Empath Examples
Date: $(date -R)

This is a test email sent through Empath MTA.

This email demonstrates:
- Basic SMTP transaction
- Email headers
- Message body

Generated by: examples/smtp-client/send_email.sh
EMAIL
    echo "."
    sleep 0.1
    echo "QUIT"
} | nc "$HOST" "$PORT"

echo ""
echo "✅ Email sent successfully!"
echo ""
echo "Next steps:"
echo "  - Check queue: just queue-list"
echo "  - View logs: RUST_LOG=debug just run"
echo "  - Monitor delivery: just queue-stats --watch"
