name: Analyze - Code Coverage

on:
  push:
    branches: ["master"]
    paths:
      - "**/*.rs"
  pull_request:
    branches: ["master"]
    paths:
      - "**/*.rs"

jobs:
  coverage:
    name: Analyze - Code Coverage
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
      CARGO_TERM_COLOR: always

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: rui314/setup-mold@v1

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly

      - name: Generate code coverage
        run: |
          cargo install cargo-tarpaulin
          cargo +nightly tarpaulin --verbose --all-features --workspace --timeout 120 --out Xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          flags: unittests
